version = 0.1
[default.pipeline_bootstrap.parameters]
oidc_provider_url = "https://token.actions.githubusercontent.com"
oidc_client_id = "sts.amazonaws.com"
github_org = "jiremv"
github_repo = "amazon-connect-iac"
deployment_branch = "main"
oidc_provider = "github-actions"
permissions_provider = "OpenID Connect (OIDC)"

[amazon-connect-iac-dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::545200407638:role/aws-sam-cli-managed-amazon-co-PipelineExecutionRole-GNPj7q9QYW6P"
cloudformation_execution_role = "arn:aws:iam::545200407638:role/aws-sam-cli-managed-amazo-CloudFormationExecutionRo-h3kr875Q8SzI"
artifacts_bucket = "aws-sam-cli-managed-amazon-connect-artifactsbucket-ko957kdncaix"
image_repository = ""
region = "us-east-1"

[amazon-connect-iac-prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::545200407638:role/aws-sam-cli-managed-amazon-co-PipelineExecutionRole-jlI0DJtcbslw"
cloudformation_execution_role = "arn:aws:iam::545200407638:role/aws-sam-cli-managed-amazo-CloudFormationExecutionRo-gtC5sfGr1LH0"
artifacts_bucket = "aws-sam-cli-managed-amazon-connect-artifactsbucket-ygd0d2xu6hdf"
image_repository = ""
region = "us-east-2"
