---
# .github/workflows/deploy-dev.yaml
name: Deploy to DEV (us-east-1)

on:
  push:
    branches:
      - develop

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Build SAM app
        run: sam build --template-file template-connect.yaml

      - name: Deploy to DEV
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          sam deploy             --template-file template-connect.yaml             --stack-name amazon-connect-iac-dev             --region us-east-1             --capabilities CAPABILITY_IAM             --s3-bucket dev-artifacts-bucket-s3-connect             --no-fail-on-empty-changeset
